# Header
menu:
  主页: /
  所有文章: /archives
  # 随笔: /tags/随笔

# SubNav
subnav:
  github: https://github.com/chalme/
  rss: /atom.xml
  # weibo: "#"
  # zhihu: "#"
  #douban: "#"
  #mail: "#"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# Content
excerpt_link: more
fancybox: true

favicon: /favicon.png

#你的头像url
avatar: /assets/blogimg/avatar.jpg

duoshuo: false
share: true
#是否开启“关于我”。
#不开启——
aboutme: false
#开启——
#aboutme: 我是谁，我从哪里来，我到哪里去？我就是我，是颜色不一样的吃货…
